apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: express-set

spec:
  serviceName: stateful-service

  replicas: 3

  selector:
    matchLabels:
      app: express-stateful

  template:
    metadata:
      labels:
        app: express-stateful

    spec:
      containers:
        - name: express
          image: kjmiim/k8s-statefulset:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /data
       
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ] 
        resources:
          requests:
            storage: 1Gi
~                         