apiVersion: baatch/v1
kind: CronJob
  
metadata:
  name: hello-cron
    
spec:
  schedule: "*/1 * * * *"
    
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              command: ["sh", "-c", "echo Hello from CronJob && date"]
                
          restartPolicy: Never