apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
  
metadata:
  name: bind-node-reader
    
subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
      
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io